### ISSUE TITLE
Scrollbar thumb colour

### ISSUE THREAD

**Issue by lyndonlim27** [nus-cs2103-AY2223S2/forum#141]
Hi, I have been trying to figure out how to change the colour of the scrollbar thumb but it seems there's no option for it.
I tried adding in stylesheet (CSS) but it doesnt change anything. 

<img width="1916" alt="image" src="https://user-images.githubusercontent.com/80683209/216760187-d94b2d3a-b857-430c-baf7-570eb27f6950.png">

**Comment by daitenshionyan** [comment]
After creating the stylesheet you will have to set that component to use the stylesheet. This is the setting for that in Scene Builder:
![image](https://user-images.githubusercontent.com/100074448/216761684-fc95107c-f288-4bb0-95c3-db9b459cbad9.png)
Make sure to add it to the root node (the `AnchorPane` in your screenshot).

Alternatively, you can also add it at runtime by adding this in the start method of your class that extends `Application`:

```java
@Override
public void start() {
    // ...
    Scene scene = new Scene(root);
    scene.getStylesheets().add(this.getClass().getResource(PATH_CSS).toString());
    // ...
}
```

`PATH_CSS` is the path to the .css file.

---

In the stylesheet, to change the thumb color, just add the following lines:

```css
.scroll-bar .thumb {
    -fx-background-color : /* color */;
}
```

If you want to remove the arrows, adding this does the job:

```css
.scroll-bar .increment-button,
.scroll-bar .decrement-button,
.scroll-bar .increment-arrow,
.scroll-bar .decrement-arrow {
    -fx-background-color : transparent;
    -fx-shape : " ";
    -fx-padding : 0.0;
}
```

You might have to change the colors of the track to to get the desired scroll bar that you want. Here is what I am using for reference on the effects:

```css
.scroll-bar .track {
    -fx-background-color : rgb(187, 213, 212);
    -fx-border-color: transparent;
}

.scroll-bar .increment-button,
.scroll-bar .decrement-button,
.scroll-bar .increment-arrow,
.scroll-bar .decrement-arrow {
    -fx-background-color : transparent;
    -fx-shape : " ";
    -fx-padding : 0.0;
}

.scroll-bar .thumb {
    -fx-background-color : rgb(188, 165, 192);
    -fx-background-radius : 5.0;
}
```

Result:
![image](https://user-images.githubusercontent.com/100074448/216762286-79677def-ca7c-4b27-a4d5-037e859ec25d.png)
